import type { TransactionType } from "@/types/Types"; 
import { defineStore } from "pinia";

export const useTransactionStore = defineStore('useTransactionStore',{
  state:() :{fullTransactions:TransactionType[]} =>({
    fullTransactions:[
      {
        transactionId: "TXN1001",
        terminalcode: 12345,
        sender: "0911123456",
        reciver: "Abel Addis",
        paymentType: "Credit Card",
        dateAndTime: "2025-04-16T10:15:30Z",
        amount: 250.75,
        bankName: "Commercial Bank of Ethiopia",
        status: "SUCCESSFULL",
        reason: "Payment for coffee and pastry order",
        casher: "Aroge Cashier"
      },
      {
        transactionId: "TXN1002",
        terminalcode: 54321,
        sender: "0922789012",
        reciver: "Abel Addis",
        paymentType: "Bank Transfer",
        dateAndTime: "2025-04-15T09:30:00Z",
        amount: 1200.00,
        bankName: "Bank of Abyssinia",
        status: "FAILED",
        reason: "Insufficient balance for large group dinner payment",
        casher: "Aroge Cashier"
      },
      {
        transactionId: "TXN1003",
        terminalcode: 98765,
        sender: "0933345678",
        reciver: "Abel Addis",
        paymentType: "Mobile Money",
        dateAndTime: "2025-04-14T14:20:45Z",
        amount: 75.50,
        bankName: "Amhara Bank",
        status: "IN PROGRESS",
        reason: "Waiting for confirmation of lunch special order",
        casher: "Aroge Cashier"
      },
      {
        transactionId: "TXN1004",
        terminalcode: 67890,
        sender: "0912345678",
        reciver: "Mikayel Teshome",
        paymentType: "Bank Transfer",
        dateAndTime: "2025-04-13T11:45:00Z",
        amount: 330.00,
        bankName: "Dasha Bank",
        status: "SUCCESSFULL",
        reason: "Payment for weekend brunch",
        casher: "Eyasu Mengistu"
      },
      {
        transactionId: "TXN1005",
        terminalcode: 11223,
        sender: "0920001122",
        reciver: "Mikayel Mekonnen",
        paymentType: "Mobile Money",
        dateAndTime: "2025-04-13T16:20:00Z",
        amount: 89.90,
        bankName: "Bank of Abyssinia",
        status: "IN PROGRESS",
        reason: "Waiting for confirmation of dessert order",
        casher: "Selam Abebe"
      },
      {
        transactionId: "TXN1006",
        terminalcode: 33445,
        sender: "0945567788",
        reciver: "Ermiyas Asfaw",
        paymentType: "Telebirr Credit Card",
        dateAndTime: "2025-04-12T08:05:00Z",
        amount: 1900.00,
        bankName: "Telebirr",
        status: "FAILED",
        reason: "Card authorization error for private event booking",
        casher: "Mariam Tufa"
      },
      {
        transactionId: "TXN1007",
        terminalcode: 55667,
        sender: "0911987654",
        reciver: "Daniel Desta",
        paymentType: "Unauthorized Payment",
        dateAndTime: "2025-04-11T13:33:33Z",
        amount: 455.25,
        bankName: "Debub Bank",
        status: "SUCCESSFULL",
        reason: "Payment received for catering services",
        casher: "Haile Gebre"
      },
      {
        transactionId: "TXN1008",
        terminalcode: 77889,
        sender: "0900789654",
        reciver: "Mesfin Gebregziabher",
        paymentType: "Mobile Banking",
        dateAndTime: "2025-04-10T17:00:00Z",
        amount: 105.10,
        bankName: "Amhara Bank",
        status: "IN PROGRESS",
        reason: "Coffee subscription renewal pending",
        casher: "Emmanuel Kebede"
      },
      {
        transactionId: "TXN1009",
        terminalcode: 22334,
        sender: "0904567890",
        reciver: "Abebech Girmay",
        paymentType: "Bank Transfer",
        dateAndTime: "2025-04-11T09:00:00Z",
        amount: 450.60,
        bankName: "Awash Bank",
        status: "SUCCESSFULL",
        reason: "Payment for anniversary dinner",
        casher: "Tesfaye Asfaw"
      },
      {
        transactionId: "TXN1010",
        terminalcode: 66789,
        sender: "0906789012",
        reciver: "Abraham Bekele",
        paymentType: "Mobile Banking",
        dateAndTime: "2025-04-12T10:15:00Z",
        amount: 250.00,
        bankName: "Commercial Bank of Ethiopia",
        status: "IN PROGRESS",
        reason: "Pending payment for wine tasting event",
        casher: "Mulugeta Woldemariam"
      },
      {
        transactionId: "TXN1011",
        terminalcode: 88900,
        sender: "0912345678",
        reciver: "Mulu Gebre",
        paymentType: "Mobile Banking",
        dateAndTime: "2025-04-13T14:30:00Z",
        amount: 120.80,
        bankName: "Dashen Bank",
        status: "SUCCESSFULL",
        reason: "Payment for coffee beans purchase",
        casher: "Yonas Gebre"
      },
      {
        transactionId: "TXN1012",
        terminalcode: 55667,
        sender: "0901234567",
        reciver: "Dawit Solomon",
        paymentType: "Bank Transfer",
        dateAndTime: "2025-04-14T13:45:00Z",
        amount: 700.50,
        bankName: "United Bank",
        status: "IN PROGRESS",
        reason: "Corporate lunch catering deposit",
        casher: "Yared Gebremariam"
      },
      {
        transactionId: "TXN1013",
        terminalcode: 33456,
        sender: "0902345678",
        reciver: "Sara Kifle",
        paymentType: "Mobile Banking",
        dateAndTime: "2025-04-15T11:00:00Z",
        amount: 180.75,
        bankName: "Zemen Bank",
        status: "SUCCESSFULL",
        reason: "Birthday cake and coffee payment",
        casher: "Bethelhem Assefa"
      },
      {
        transactionId: "TXN1014",
        terminalcode: 22345,
        sender: "0908765432",
        reciver: "Lemlem Tewelde",
        paymentType: "Mobile Banking",
        dateAndTime: "2025-04-16T16:15:00Z",
        amount: 350.90,
        bankName: "Bank of Abyssinia",
        status: "SUCCESSFULL",
        reason: "Payment for beer and burger special",
        casher: "Fikremariam Tsegaye"
      },
      {
        transactionId: "TXN1015",
        terminalcode: 99876,
        sender: "0901122334",
        reciver: "Wondimu Hagos",
        paymentType: "Bank Transfer",
        dateAndTime: "2025-04-17T10:30:00Z",
        amount: 580.50,
        bankName: "Commercial Bank of Ethiopia",
        status: "IN PROGRESS",
        reason: "Pending payment for private dining room reservation",
        casher: "Mekonnen Belay"
      },
      {
        transactionId: "TXN1016",
        terminalcode: 88765,
        sender: "0902345679",
        reciver: "Mekdes Tesfaye",
        paymentType: "Mobile Banking",
        dateAndTime: "2025-04-18T12:00:00Z",
        amount: 130.90,
        bankName: "Awash Bank",
        status: "SUCCESSFULL",
        reason: "Payment for afternoon tea service",
        casher: "Abebe Tadesse"
      },
      {
        transactionId: "TXN1017",
        terminalcode: 99878,
        sender: "0905566778",
        reciver: "Tigist Ghebremedhin",
        paymentType: "Mobile Banking",
        dateAndTime: "2025-04-19T09:30:00Z",
        amount: 75.50,
        bankName: "NIB International Bank",
        status: "SUCCESSFULL",
        reason: "Breakfast combo payment",
        casher: "Mulugeta Woldemariam"
      },
      {
        transactionId: "TXN10188",
        terminalcode: 77654,
        sender: "0907890123",
        reciver: "Selam Tesfaye",
        paymentType: "Bank Transfer",
        dateAndTime: "2025-04-20T14:45:00Z",
        amount: 220.00,
        bankName: "Dashen Bank",
        status: "IN PROGRESS",
        reason: "Pending payment for barista workshop",
        casher: "Addis Gashaw"
      },
      {
        transactionId: "TXN1019",
        terminalcode: 55432,
        sender: "0912345679",
        reciver: "Dawit Asfaw",
        paymentType: "Mobile Banking",
        dateAndTime: "2025-04-21T11:00:00Z",
        amount: 500.00,
        bankName: "United Bank",
        status: "SUCCESSFULL",
        reason: "Payment for coffee machine purchase",
        casher: "Tesfaye Asfaw"
      },
      {
        transactionId: "TXN1020",
        terminalcode: 33221,
        sender: "0908765432",
        reciver: "Kebede Tesfaye",
        paymentType: "Bank Transfer",
        dateAndTime: "2025-04-22T13:15:00Z",
        amount: 150.25,
        bankName: "Zemen Bank",
        status: "IN PROGRESS",
        reason: "Pending payment for artisanal cheese platter",
        casher: "Mekonnen Belay"
      },
      {
        transactionId: "TXN1021",
        terminalcode: 77889,
        sender: "0902345678",
        reciver: "Samiha Bekele",
        paymentType: "Mobile Banking",
        dateAndTime: "2025-04-23T12:30:00Z",
        amount: 250.00,
        bankName: "Bank of Abyssinia",
        status: "SUCCESSFULL",
        reason: "Gift card purchase for cafe",
        casher: "Yared Gebremariam"
      },
      {
        transactionId: "TXN1022",
        terminalcode: 33556,
        sender: "0902345678",
        reciver: "Mulu Ayele",
        paymentType: "Mobile Banking",
        dateAndTime: "2025-04-24T16:00:00Z",
        amount: 300.00,
        bankName: "Awash Bank",
        status: "SUCCESSFULL",
        reason: "Wedding reception coffee service deposit",
        casher: "Mulugeta Woldemariam"
      },
      {
        transactionId: "TXN1023",
        terminalcode: 55667,
        sender: "0901234567",
        reciver: "Biruk Tesfaye",
        paymentType: "Bank Transfer",
        dateAndTime: "2025-04-25T10:30:00Z",
        amount: 125.75,
        bankName: "NIB International Bank",
        status: "SUCCESSFULL",
        reason: "Payment for bar snacks and drinks",
        casher: "Bethelhem Assefa"
      },
      {
        transactionId: "TXN1024",
        terminalcode: 22334,
        sender: "0912345678",
        reciver: "Yonas Woldemariam",
        paymentType: "Mobile Banking",
        dateAndTime: "2025-04-26T15:30:00Z",
        amount: 270.50,
        bankName: "Commercial Bank of Ethiopia",
        status: "IN PROGRESS",
        reason: "Pending payment for coffee subscription",
        casher: "Abebe Tadesse"
      },
      {
        transactionId: "TXN1025",
        terminalcode: 77889,
        sender: "0903456789",
        reciver: "Liya Gebre",
        paymentType: "Bank Transfer",
        dateAndTime: "2025-04-27T11:15:00Z",
        amount: 500.00,
        bankName: "Bank of Abyssinia",
        status: "SUCCESSFULL",
        reason: "Payment for private wine tasting event",
        casher: "Mulugeta Woldemariam"
      },
      {
        transactionId: "TXN1026",
        terminalcode: 55678,
        sender: "0916789012",
        reciver: "Tsegaye Kebede",
        paymentType: "Mobile Banking",
        dateAndTime: "2025-04-28T13:00:00Z",
        amount: 100.00,
        bankName: "United Bank",
        status: "SUCCESSFULL",
        reason: "Payment for coffee and dessert",
        casher: "Mekonnen Belay"
      },
      {
        transactionId: "TXN1027",
        terminalcode: 33221,
        sender: "0902345678",
        reciver: "Amir Hagos",
        paymentType: "Mobile Banking",
        dateAndTime: "2025-04-29T12:00:00Z",
        amount: 120.00,
        bankName: "Zemen Bank",
        status: "IN PROGRESS",
        reason: "Pending payment for lunch special",
        casher: "Yared Gebremariam"
      },
      {
        transactionId: "TXN1001",
        terminalcode: 12345,
        sender: "0912345678",
        reciver: "John Doe",
        paymentType: "Bank Transfer",
        dateAndTime: "2025-04-01T10:30:00Z",
        amount: 250.75,
        bankName: "Commercial Bank of Ethiopia",
        status: "SUCCESSFULL",
        reason: "Payment for coffee catering service",
        casher: "Abebe Tadesse"
      },
      {
        transactionId: "TXN1002",
        terminalcode: 67890,
        sender: "0919876543",
        reciver: "Sara Ali",
        paymentType: "Mobile Banking",
        dateAndTime: "2025-04-02T11:45:00Z",
        amount: 350.20,
        bankName: "Awash Bank",
        status: "SUCCESSFULL",
        reason: "Payment for barista workshop",
        casher: "Mekonnen Belay"
      },
      {
        transactionId: "TXN1004",
        terminalcode: 44567,
        sender: "0901122334",
        reciver: "Lily Tesfaye",
        paymentType: "Mobile Banking",
        dateAndTime: "2025-04-04T09:15:00Z",
        amount: 120.50,
        bankName: "United Bank",
        status: "SUCCESSFULL",
        reason: "Payment for coffee beans subscription",
        casher: "Fikremariam Tsegaye"
      },
      {
        transactionId: "TXN1005",
        terminalcode: 33456,
        sender: "0905566778",
        reciver: "Solomon Welde",
        paymentType: "Bank Transfer",
        dateAndTime: "2025-04-05T13:20:00Z",
        amount: 700.00,
        bankName: "Bank of Abyssinia",
        status: "SUCCESSFULL",
        reason: "Corporate coffee machine purchase",
        casher: "Bethelhem Assefa"
      },
      {
        transactionId: "TXN1006",
        terminalcode: 99877,
        sender: "0902345670",
        reciver: "Getachew Hailu",
        paymentType: "Mobile Banking",
        dateAndTime: "2025-04-06T16:00:00Z",
        amount: 315.40,
        bankName: "Dashen Bank",
        status: "IN PROGRESS",
        reason: "Pending payment for espresso machine repair",
        casher: "Addis Gashaw"
      },
      {
        transactionId: "TXN1007",
        terminalcode: 55678,
        sender: "0908765432",
        reciver: "Tadelech Teshome",
        paymentType: "Mobile Banking",
        dateAndTime: "2025-04-07T12:30:00Z",
        amount: 200.00,
        bankName: "NIB International Bank",
        status: "SUCCESSFULL",
        reason: "Payment for cafe furniture",
        casher: "Biniam Solomon"
      },
      {
        transactionId: "TXN1008",
        terminalcode: 77889,
        sender: "0900789654",
        reciver: "Mesfin Gebregziabher",
        paymentType: "Mobile Banking",
        dateAndTime: "2025-04-10T17:00:00Z",
        amount: 105.10,
        bankName: "Amhara Bank",
        status: "IN PROGRESS",
        reason: "Pending payment for coffee tasting event",
        casher: "Emmanuel Kebede"
      },
      {
        transactionId: "TXN1009",
        terminalcode: 56123,
        sender: "0911123456",
        reciver: "Abebe Tadesse",
        paymentType: "ATM Withdrawal",
        dateAndTime: "2025-03-28T09:15:00Z",
        amount: 1200.00,
        bankName: "Awash Bank",
        status: "SUCCESSFULL",
        reason: "Cafe equipment purchase",
        casher: "Mulugeta Alemu"
      },
      {
        transactionId: "TXN1010",
        terminalcode: 77441,
        sender: "0922234567",
        reciver: "Kebede Alemayehu",
        paymentType: "POS Payment",
        dateAndTime: "2025-03-21T13:00:00Z",
        amount: 320.75,
        bankName: "Zemen Bank",
        status: "SUCCESSFULL",
        reason: "Payment for cafe lunch buffet",
        casher: "Rahel Tesfaye"
      },
      {
        transactionId: "TXN1011",
        terminalcode: 88990,
        sender: "0933345678",
        reciver: "Sara Yohannes",
        paymentType: "Mobile Banking",
        dateAndTime: "2025-03-18T11:45:00Z",
        amount: 90.50,
        bankName: "Dashen Bank",
        status: "FAILED",
        reason: "Insufficient balance for coffee order",
        casher: "Tigist Mekonnen"
      },
      {
        transactionId: "TXN1012",
        terminalcode: 90012,
        sender: "0944456789",
        reciver: "Fikadu Daniel",
        paymentType: "Account Transfer",
        dateAndTime: "2025-03-08T08:20:00Z",
        amount: 700.00,
        bankName: "Nib Bank",
        status: "SUCCESSFULL",
        reason: "Monthly coffee supply payment",
        casher: "Eyob Worku"
      },
      {
        transactionId: "TXN1013",
        terminalcode: 32123,
        sender: "0955567890",
        reciver: "Mekdes Abera",
        paymentType: "Unauthorized Payment",
        dateAndTime: "2025-03-02T15:10:00Z",
        amount: 600.00,
        bankName: "Wegagen Bank",
        status: "IN PROGRESS",
        reason: "Pending approval for catering deposit",
        casher: "Samuel Tekle"
      },
      {
        transactionId: "TXN1003",
        terminalcode: 11223,
        sender: "0913456789",
        reciver: "Martha Kifle",
        paymentType: "Mobile Banking",
        dateAndTime: "2025-03-11T14:00:00Z",
        amount: 500.00,
        bankName: "Zemen Bank",
        status: "IN PROGRESS",
        reason: "Pending payment for private dining event",
        casher: "Yared Gebremariam"
      },
      {
        transactionId: "TXN1014",
        terminalcode: 45231,
        sender: "0916677889",
        reciver: "Marta Abate",
        paymentType: "Mobile Banking",
        dateAndTime: "2025-02-27T10:30:00Z",
        amount: 150.00,
        bankName: "Enat Bank",
        status: "SUCCESSFULL",
        reason: "Payment for coffee workshop",
        casher: "Abel Desta"
      },
      {
        transactionId: "TXN1015",
        terminalcode: 33445,
        sender: "0927788990",
        reciver: "Yonas Tefera",
        paymentType: "ATM Withdrawal",
        dateAndTime: "2025-02-22T12:50:00Z",
        amount: 500.00,
        bankName: "Commercial Bank",
        status: "FAILED",
        reason: "Card blocked for cafe purchase",
        casher: "Betty Adamu"
      },
      {
        transactionId: "TXN1016",
        terminalcode: 99887,
        sender: "0938899001",
        reciver: "Selamawit Asfaw",
        paymentType: "POS Payment",
        dateAndTime: "2025-02-16T17:20:00Z",
        amount: 250.00,
        bankName: "Bunna Bank",
        status: "SUCCESSFULL",
        reason: "Payment for wine and cheese pairing event",
        casher: "Brook Ayele"
      },
      {
        transactionId: "TXN1017",
        terminalcode: 11002,
        sender: "0949900112",
        reciver: "Kassahun Mengesha",
        paymentType: "Account Transfer",
        dateAndTime: "2025-02-11T14:30:00Z",
        amount: 850.00,
        bankName: "Lion Bank",
        status: "IN PROGRESS",
        reason: "Transfer for cafe renovation deposit",
        casher: "Hana Solomon"
      },
      {
        transactionId: "TXN1018",
        terminalcode: 22334,
        sender: "0950011223",
        reciver: "Eleni Fekadu",
        paymentType: "Unauthorized Payment",
        dateAndTime: "2025-02-03T18:00:00Z",
        amount: 975.30,
        bankName: "Cooperative Bank",
        status: "SUCCESSFULL",
        reason: "Payment for coffee farm tour package",
        casher: "Fitsum Lemma"
      }
    ]
    
  }),
  actions: {
    getTransaction(id: string) {
      return this.fullTransactions.find((t) => t.transactionId === id);
    },
    addTransaction({
      amount,
      sender,
      bank,
      paymentType,
    }: {
      amount: number;
      sender: string;
      bank: string;
      paymentType: string;
    }) {
      const newTransaction: TransactionType = {
        transactionId: `TXN${Math.floor(10000 + Math.random() * 90000)}`,
        terminalcode: Math.floor(10000 + Math.random() * 90000),
        sender: sender,
        reciver: "Abel Addis",
        paymentType,
        dateAndTime: new Date().toISOString(),
        amount,
        bankName: bank,
        status: "SUCCESSFULL",
        reason: "for service charge for work room",
        casher: "cahser1",
      };
  
      this.fullTransactions.push(newTransaction);
    }
  }
  
})


// ethio dumy transaction
// const transactions: TransactionType[] = [
//   {
//     transactionId: "TXN1001",
//     terminalcode: 12345,
//     sender: "0911123456",
//     reciver: "አቤል አዲስ",
//     paymentType: "ክሬዲት ካርድ",
//     dateAndTime: "2025-04-16T10:15:30Z",
//     amount: 250.75,
//     bankName: "ኢትዮጵያ ባንክ",
//     status: "ተሳክቷል",
//     reason: "መክፈያው ተጠናቋል",
//     casher: "አሮጌ ካሺየር"
//   },
//   {
//     transactionId: "TXN1002",
//     terminalcode: 54321,
//     sender: "0922789012",
//     reciver: "አቤል አዲስ",
//     paymentType: "ባንክ ማስተላለፊያ",
//     dateAndTime: "2025-04-15T09:30:00Z",
//     amount: 1200.00,
//     bankName: "አብሲኒያ ባንክ",
//     status: "አልተሳካም",
//     reason: "በመለያው ላይ በቂ ተመን የለም",
//     casher: "አሮጌ ካሺየር"
//   },
//   {
//     transactionId: "TXN1003",
//     terminalcode: 98765,
//     sender: "0933345678",
//     reciver: "አቤል አዲስ",
//     paymentType: "ሞባይል ገንዘብ",
//     dateAndTime: "2025-04-14T14:20:45Z",
//     amount: 75.50,
//     bankName: "አማራ ባንክ",
//     status: "በሂደት ላይ",
//     reason: "ማረጋገጫ በመጠበቅ ላይ",
//     casher: "አሮጌ ካሺየር"
//   },
//   {
//     transactionId: "TXN1004",
//     terminalcode: 67890,
//     sender: "0912345678",
//     reciver: "ሚካኤል ተሾመ",
//     paymentType: "ባንክ ማስተላለፊያ",
//     dateAndTime: "2025-04-13T11:45:00Z",
//     amount: 330.00,
//     bankName: "ዳሳ ባንክ",
//     status: "ተሳክቷል",
//     reason: "ተቀባዩ መለያ ትክክል ነው",
//     casher: "ኢያሱ መንግስቱ"
//   },
//   {
//     transactionId: "TXN1005",
//     terminalcode: 11223,
//     sender: "0920001122",
//     reciver: "ሚካኤል መኮንን",
//     paymentType: "ሞባይል ገንዘብ",
//     dateAndTime: "2025-04-13T16:20:00Z",
//     amount: 89.90,
//     bankName: "ባንክ ኦፍ አቢሲኒያ",
//     status: "በሂደት ላይ",
//     reason: "የተቀባዩ ማረጋገጫ በመጠበቅ ላይ",
//     casher: "ሰላም አበበ"
//   },
//   {
//     transactionId: "TXN1006",
//     terminalcode: 33445,
//     sender: "0945567788",
//     reciver: "ኤርሚያስ አስፋው",
//     paymentType: "ቲሌ ባንክ ክሪዲት ካርድ",
//     dateAndTime: "2025-04-12T08:05:00Z",
//     amount: 1900.00,
//     bankName: "ቲሌ ባንክ",
//     status: "አልተሳካም",
//     reason: "የካርዱ አረፋዊ ችግር",
//     casher: "ማርያም ቱፋ"
//   },
//   {
//     transactionId: "TXN1007",
//     terminalcode: 55667,
//     sender: "0911987654",
//     reciver: "ዳንኤል ደስታ",
//     paymentType: "ባለ ህገወጥ ክፍያ",
//     dateAndTime: "2025-04-11T13:33:33Z",
//     amount: 455.25,
//     bankName: "ደቡብ ባንክ",
//     status: "ተሳክቷል",
//     reason: "በተሳካ መልኩ ተቀባ",
//     casher: "ሃይለ ገብረ"
//   },
//   {
//     transactionId: "TXN1008",
//     terminalcode: 77889,
//     sender: "0900789654",
//     reciver: "መስፍን ገብረእግዚአብሔር",
//     paymentType: "ሞባይል ባንኪንግ",
//     dateAndTime: "2025-04-10T17:00:00Z",
//     amount: 105.10,
//     bankName: "አማራ ባንክ",
//     status: "በሂደት ላይ",
//     reason: "የተቀባዩ መለያ በምስጢር ቁጥር ተጠቀም",
//     casher: "አማኑኤል ከበደ"
//   }


// ];